### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Systemad** [franciscofranco/bullhead#2]
Hello, I'm trying to compile your kernel with some other governors I added my own, however, when compiling I always left with this error

![fraanco](https://cloud.githubusercontent.com/assets/8531546/24074757/1e6281cc-0c0f-11e7-9ca1-3893d76dd259.PNG)

and obviously, I tried compiling straight from your source (with no changes) and still get this error.
I'm using this toolchain
 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9

I build with

```
make bullhead_defconfig
make -j4 (I've tried with make ARCH=arm64 too)
```

 I'm on Linux 14.04 on virtual box
don't now what more info I could provide.

thank you

**Comment by DespairFactor** [comment]
@Systemad You will need to enable the kcal driver in the defconfig

**Comment by Systemad** [comment]
@DespairFactor forgot about that lol, added it and compiles fine now. Thanks!

Will lose this issue now

**Comment by Systemad** [comment]
looks like it doesn't boot, before I investigate why.
is this something  to worry about?
![capture](https://cloud.githubusercontent.com/assets/8531546/24083032/da0d0dd2-0ccf-11e7-90ce-8d4bea9e040a.PNG)
